### ISSUE TITLE
请问海底捞小程序的openid用什么工具抓取

### ISSUE THREAD

**Issue by gitcps** [wjf0214/qd-templates#151]

**Comment by gitcps** [comment]
手机抓包软件无法正常获取，只能获取到token

**Comment by wjf0214** [comment]
> 手机抓包软件无法正常获取，只能获取到token

小程序退出登录后，开启抓包软件，抓取登录的请求。如果是微信登录，可以看看`login/safeBind`这个请求传递的参数，里面有需要的参数。其他登录方式也是看对应的登录请求就是。
