### ISSUE TITLE
98堂签到10/15错误

### ISSUE THREAD

**Issue by XiaoYeah6** [wjf0214/qd-templates#152]
大佬请问下出现这个报错是哪里出错了啊，填写了domain为“[https://sehuatang.net/”](https://sehuatang.net/%E2%80%9D)
Failed at 10/15 request,
Fail assert: {"re": "invalid", "from": "content"} from failed_asserts,
Request URL: {{domain}}misc.php?mod=secqaa&action=check&inajax=1&modid=&idhash={{idhash|urlencode}}&secverify={{sum|urlencode}}

**Comment by wjf0214** [comment]
> 大佬请问下出现这个报错是哪里出错了啊，填写了domain为“[https://sehuatang.net/”](https://sehuatang.net/%E2%80%9D) Failed at 10/15 request, Fail assert: {"re": "invalid", "from": "content"} from failed_asserts, Request URL: {{domain}}misc.php?mod=secqaa&action=check&inajax=1&modid=&idhash={{idhash|urlencode}}&secverify={{sum|urlencode}}

我没有账号，不太方便测试。
做模板的时候是别人提供账号做的。
不过我问了下别人是可以正常使用的。如果还不行，可以换个地址试试。

**Comment by wjf0214** [comment]
> 大佬请问下出现这个报错是哪里出错了啊，填写了domain为“[https://sehuatang.net/”](https://sehuatang.net/%E2%80%9D) Failed at 10/15 request, Fail assert: {"re": "invalid", "from": "content"} from failed_asserts, Request URL: {{domain}}misc.php?mod=secqaa&action=check&inajax=1&modid=&idhash={{idhash|urlencode}}&secverify={{sum|urlencode}}

我没有账号，不太方便测试。
做模板的时候是别人提供账号做的。
不过我问了下别人是可以正常使用的。如果还不行，可以换个地址试试。
