### ISSUE TITLE
新赚吧签到失效了

### ISSUE THREAD

**Issue by kokpk** [wjf0214/qd-templates#153]
21号开始失效了报错如下：
Failed at 4/7 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 302: Found,
Request URL: https://v1.xianbao.net/plugin.php?id=dsu_paulsign%3Asign&operation=qiandao&infloat=0&inajax=0

**Comment by wjf0214** [comment]
> 21号开始失效了报错如下： Failed at 4/7 request, Fail assert: {"re": "200", "from": "status"} from success_asserts, Response Error : HTTP 302: Found, Request URL: [v1.xianbao.net/plugin.php?id=dsu_paulsign%3Asign&operation=qiandao&infloat=0&inajax=0](https://v1.xianbao.net/plugin.php?id=dsu_paulsign%3Asign&operation=qiandao&infloat=0&inajax=0)

已更新。
