### ISSUE TITLE
阡陌居Har包有问题

### ISSUE THREAD

**Issue by SoftwarePianist** [wjf0214/qd-templates#154]
![image](https://user-images.githubusercontent.com/21188142/215056767-ec4fbe88-5d5f-4fa3-a8e1-dd41b2af4e25.png)

全新导入，直接报如图错误，加上帐号和密码也是一样的错

**Comment by wjf0214** [comment]
![image](https://user-images.githubusercontent.com/23102821/215302874-72f5ee1f-ab27-4f62-86b9-5d87f3df88c2.png)
看下这个注意事项说明，你应该是从主页直接下载的模板，请从 [阡陌居.har](https://raw.githubusercontent.com/wjf0214/qd-templates/master/阡陌居.har) 的地址下载。
