### ISSUE TITLE
tekqart 签到有成功的嘛

### ISSUE THREAD

**Issue by chinatengjie** [wjf0214/qd-templates#174]
Failed at 2/12 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 599: Operation timed out after 30003 milliseconds with 0 bytes received,
Request URL: {{flaresolverrUrl}}

Failed at 2/12 request,
Fail assert: {"re": "\"status\": \"error\"", "from": "content"} from failed_asserts,
Request URL: {{flaresolverrUrl}}

api 地址 填的 http://192.168.1233.12:8191/v1

docker 用的 15cm/flaresolverr 3.0.0

**Comment by chinatengjie** [comment]
可以了

**Comment by chinatengjie** [comment]
可以了

**Comment by huoshenw** [comment]
我也是这个报错 大佬怎么解决的

**Comment by wjf0214** [comment]
> 我也是这个报错 大佬怎么解决的

这是请求超时，手动有可能过cf盾的时候会超时，添加完成后可以等自动的看看。没问题就OK。
