### ISSUE TITLE
大佬，花火学园，过盾后报599

### ISSUE THREAD

**Issue by love768952693** [wjf0214/qd-templates#175]
大佬，花火学园，过盾后报599

**Comment by wjf0214** [comment]
我这边正常，599可能是网络问题？

**Comment by love768952693** [comment]
> 我这边正常，599可能是网络问题？

`2023-04-27 18:46:09
日志：Failed at 1/7 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 599: Operation timed out after 30001 milliseconds with 0 bytes received,
Request URL: {{flaresolverrUrl}}`

大佬好奇怪啊，列表其它的正常，就花火这边有问题，品技同样过盾没问题。

**Comment by wjf0214** [comment]
超时了，过盾时间超过半分钟就直接终止了。

**Comment by youlan2333** [comment]
签到失败
用户：【】，等级：【】
签到情况：【签到成功】
学分：【】，经验：【】，烟花：【】，贡献：【】，勋章兑换券：【】，积分：【】
