### ISSUE TITLE
求大佬更新天翼云盘。

### ISSUE THREAD

**Issue by Tincichow** [wjf0214/qd-templates#177]
今天发现天翼云盘更新了，原来的签到用不了了。

**Comment by wjf0214** [comment]
更新了，你试试。

**Comment by qinxs** [comment]
> 更新了，你试试。

能否说明下 接口变动了什么吗？

我是用的python的 也失败了 通过搜索看到你这儿已经解决了

**Comment by wjf0214** [comment]
> > 更新了，你试试。
> 
> 能否说明下 接口变动了什么吗？
> 
> 我是用的python的 也失败了 通过搜索看到你这儿已经解决了

我不知道你python的是怎么实现的。我今天看，他页面获取的一些参数转移到其他接口获取了。
比如说302跳转获取的reqid和lt信息，APP信息的接口里的`paramId`信息，encrypt接口里的rsa的key，以及登录请求的post参数也都改变了。
简单来说就是之前从页面获取的登录请求的参数信息，要从其他多个接口请求获取了。最后再模拟登录就行了。

**Comment by qinxs** [comment]
好的 感谢
