### ISSUE TITLE
时光相册无法正常签到

### ISSUE THREAD

**Issue by DreamerDK** [wjf0214/qd-templates#180]
老版本的使用加密后的数据，还有新版本直接填写账号密码的，这两天都遇到了失败。
提示词也是一样的。
![image](https://github.com/wjf0214/qd-templates/assets/5880281/a7e81bd6-3d31-4fb9-b086-a49e01971814)

**Comment by wjf0214** [comment]
账号都正常吗？单从信息上来看，是登录有问题，token获取有问题。但是我做了登录判断。可能还是其他错误。。可以单条依次测试执行一下看看信息。。

**Comment by DreamerDK** [comment]
> 账号都正常吗？单从信息上来看，是登录有问题，token获取有问题。但是我做了登录判断。可能还是其他错误。。可以单条依次测试执行一下看看信息。。

单步测试下来是token和level获取失败了，因为响应的数据是乱码，猜测可能是编码问题。
测试结果：

![image](https://github.com/wjf0214/qd-templates/assets/5880281/bece19ff-0508-43d2-9a86-84824567da13)

**Comment by wjf0214** [comment]
我这边无法复现，返回都是正常的。可以看看结果返回的 ContentType 字段是不是utf-8。或者尝试调整一下header里的ContentType试试？

**Comment by DreamerDK** [comment]
我可能找到了原因？
在签到时，终端会报错误。

`[W 230521 19:32:20 QD.Http.Fetcher fetcher:475] POST https://web.everphoto.cn/api/auth [Warning] HTTP 599: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings. -> Try to retry!`

可能是因为前两天更新了 qd 的版本造成的？也可能是其他原因？反正目前应该是由于 `libcurl`只能解析 `deflate` 和 `gzip` ,但`request`中还有一个 `br`。
我**将 request 中的 accept-encoding 项取消就解决了**（我尝试删除 `br`，会报错误）

取消 `accept-encoding` ：
![image](https://github.com/wjf0214/qd-templates/assets/5880281/17062b5f-3352-4588-ade0-2bd50876e332)
