### ISSUE TITLE
98堂现在需要至少回一次贴才能签到了，能否优化下

### ISSUE THREAD

**Issue by tyhunter** [wjf0214/qd-templates#191]
例如随机找个帖子回复一下再执行签到

**Comment by wjf0214** [comment]
理论上是可行的，只是回复帖子的话，有一定风险。一直发重复一句话的话，估计可能会封号吧？

**Comment by wjf0214** [comment]
理论上是可行的，只是回复帖子的话，有一定风险。
一直发重复一句话的话，估计可能会封号吧？
我记得有人给我说过，他做过自动回复，然后没多久号被封了。
而且做的时候是别人提供账号做的，我是没账号的，维护起来麻烦点。

有时间，有机会的话，后续看情况可能会更新下，不过酌情使用吧。
