### ISSUE TITLE
请问，哪位兄台指点下aihao的打卡时间设置呀，那个num怎么填呀

### ISSUE THREAD

**Issue by xuexijiaoben** [wjf0214/qd-templates#192]
num为数字，对应值及意思为：
1.早上8-9点之间打卡。
2.下午13-14点直接打卡
3.晚上18-19点直接打卡
4.每月全勤大于60次打卡
建议前3个设置为每天对应的时间执行，每月的可以设置为cron方式执行，如【0 9 28-31 * *】

抱歉没看太明白，昨天刚开始学习这个签到框架，那个num里怎么填呀，是填
1,2,3,0 9 28-31 * *
这个么？如果这么填，这个设置跟框架里的定时怎么搭配呀

还是我要添加4个任务，分别设置上述时间呀，
非常感谢

**Comment by wjf0214** [comment]
添加4个任务。不同值设置不同的定时。
