### ISSUE TITLE
兼容阿里云盘签到的错误报错提示

### ISSUE THREAD

**Issue by AllenPu2020** [wjf0214/qd-templates#193]
api: https://member.aliyundrive.com/v1/activity/sign_in_reward

正常签到成功后，奖励信息的字段是：name、description

当会员过期后，阿里云盘空间没有清理情况下是无法领取奖励的
报错如下：
```json
{
    "code": "InternalError",
    "message": "容量超限领取失败，开通会员或清理空间后继续领取",
    "requestId": "0a0080................20e14a0"
}
```

**Comment by wjf0214** [comment]
没看懂是要干什么？是要这种情况下加上错误验证吗？

**Comment by AllenPu2020** [comment]
> 没看懂是要干什么？是要这种情况下加上错误验证吗？

因为出现这种情况时，用户看不到报错信息。不知道为什么领取奖励失败。
还以为部署的服务出现了问题
这个接口我用 postman 请求接口才发现的错误信息。

**Comment by wjf0214** [comment]
> > 没看懂是要干什么？是要这种情况下加上错误验证吗？
> 
> 因为出现这种情况时，用户看不到报错信息。不知道为什么领取奖励失败。 还以为部署的服务出现了问题 这个接口我用 postman 请求接口才发现的错误信息。

了解，根据你的提示增加了验证。
