### ISSUE TITLE
HIFINI加入了人机验证

### ISSUE THREAD

**Issue by jane77u** [wjf0214/qd-templates#198]
![image](https://github.com/wjf0214/qd-templates/assets/39855954/bd741569-12a8-43fe-93d5-23494ba62415)
想问下大佬，这个后续有无办法解决。

**Comment by wjf0214** [comment]
已更新。

**Comment by jane77u** [comment]
> 已更新。

感谢大佬

**Comment by jane77u** [comment]
> 已更新。

大佬，今天签到出现了这样的提示。（似乎是更改了人机验证的校验方式）
![屏幕截图 2023-12-25 111511](https://github.com/wjf0214/qd-templates/assets/39855954/d22dcb33-d269-44fc-8521-b9ba6fd7a05b)

还想请教一下，下面的两个参数要填写吗，在那里获取呢？
![屏幕截图 2023-12-25 112847](https://github.com/wjf0214/qd-templates/assets/39855954/e5821a1f-c27d-4691-a64a-9c3f83156f56)
麻烦大佬看看。
