### ISSUE TITLE
能帮忙看下什么问题吗，谢谢

### ISSUE THREAD

**Issue by sunny7010** [wjf0214/qd-templates#200]
HAR数据：
`[{"request":{"method":"GET","url":"https://youthstudy.12355.net/saomah5/api/young/chapter/new","headers":[{"name":"Accept-Language","value":"zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"},{"name":"Connection","value":"keep-alive"},{"name":"Host","value":"youthstudy.12355.net"},{"name":"Sec-Fetch-Dest","value":"empty\n"},{"name":"Sec-Fetch-Mode","value":"cors"},{"name":"Sec-Fetch-Site","value":"same-origin"},{"name":"User-Agent","value":"MicroMessenger"},{"name":"Referer","value":"https://youthstudy.12355.net/h5/"},{"name":"X-Requested-With","value":"com.tencent.mm"},{"name":"X-Litemall-Token","value":" "},{"name":"Accept","value":"*/*"},{"name":"X-Litemall-IdentiFication","value":"young"}],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"name":"StudyName","re":"\"name\":\"(.*?)\"","from":"content"},{"name":"updateDate","re":"\"updateDate\":\"(.*?)\"","from":"content"},{"name":"url","re":"\"url\":\"(.*?)\"","from":"content"}]}}]`
自己创建了一个青年大学习的学习提醒，只是提醒不用自动完成，这个api可以获取最新的课程信息，希望能输出名称、更新日期和学习链接，但为什么执行之后日志显示None

**Comment by wjf0214** [comment]
日志提示`None`的话应该是没有归到`__log__`变量里。执行后日志显示的内容为`__log__`变量的内容。
把你要提取的信息整理好放到`__log__`里就行了。

**Comment by sunny7010** [comment]
![Clip_2024-01-08_22-16-57](https://github.com/wjf0214/qd-templates/assets/52040067/5f17a10c-8222-47ab-bbf0-765e0e7aab12)
这样吗？假设输出课程名称，但是这样调整之后日志还是None

**Comment by wjf0214** [comment]
![image](https://github.com/wjf0214/qd-templates/assets/23102821/c809f4d8-5d90-4af4-9215-1ffae4435b29)
有的啊，测试看了。
